### ISSUE TITLE
errors: path and stack synthesizer

### ISSUE THREAD

**Issue by zoli-kasa** [incompass/aws-cdk-elasticsearch-index#80]
i'm trying to use version 1.0.0-alpha.9

Error: ENOENT: no such file or directory, stat 'dir\node_modules\@casechek\aws-cdk-elasticsearch-index\dist\dist\src\on-event'

dir/node_modules/@casechek/aws-cdk-elasticsearch-index/dist/lib/index.js:26 
code: aws_lambda_1.Code.fromAsset(path.join(__dirname, '..', 'dist', 'src', 'on-event')),

when i fix this by removing 'dist' from here:
```
dir\node_modules\@aws-cdk\custom-resources\node_modules\@aws-cdk\aws-s3-assets\lib\asset.ts:138
    const location = stack.synthesizer.addFileAsset({
                                       ^
TypeError: Cannot read property 'addFileAsset' of undefined
    at new Asset (dir\node_modules\@aws-cdk\custom-resources\node_modules\@aws-cdk\aws-s3-assets\lib\asset.ts:138:40)
    at AssetCode.bind (dir\node_modules\@aws-cdk\custom-resources\node_modules\@aws-cdk\aws-lambda\lib\code.ts:180:20)
    at new Function (dir\node_modules\@aws-cdk\custom-resources\node_modules\@aws-cdk\aws-lambda\lib\function.ts:502:29)
    at Provider.createFunction (dir\node_modules\@aws-cdk\custom-resources\lib\provider-framework\provider.ts:135:16)
    at new Provider (dir\node_modules\@aws-cdk\custom-resources\lib\provider-framework\provider.ts:100:34)
    at new ElasticsearchIndex (dir\node_modules\@casechek\aws-cdk-elasticsearch-index\lib\index.ts:61:22)
```

what should i do?

**Comment by zoli-kasa** [comment]
i upgraded to alpha.17, it works now
